version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: build/server.Dockerfile
    ports:
      - "9000:9000"
    environment:
      SERVER_LISTEN_ADDR: "0.0.0.0:9000"
      SERVER_MAX_CONNECTIONS: "100"
      SERVER_TIMEOUT: "5000"
      SERVER_POW_BASE_DIFFICULTY: "3"
      SERVER_POW_MAX_DIFFICULTY: "6"
      SERVER_POW_WINDOW_SIZE: "100"
      SERVER_POW_WINDOW_DURATION: "1m"
    restart: always

  client:
    build:
      context: .
      dockerfile: build/client.Dockerfile
    depends_on:
      - server
    environment:
      CLIENT_SERVER_ADDR: "server:9000"
      CLIENT_FETCH_WORKERS: "4"
      CLIENT_TIMEOUT: "1000"
    restart: on-failure
